### ISSUE TITLE
To Dos

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/docker-images#10]
* [x] Docker hub upload on success after push to master
 * [x] Test on py3 as well as py2 on all platforms where it's available. 
 * [x] pull test.sh out into the source directory instead of inline in the Dockerfile

**Comment by hugovk** [comment]
See https://github.com/python-pillow/docker-images/pull/27 for number 3.

**Comment by hugovk** [comment]
Number 2 done by https://github.com/python-pillow/docker-images/pull/42.
