### ISSUE TITLE
Proposal: Reduce testing, push on latest rather than stable

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/docker-images#108]
So, a bit of history here -- these images were originally setup to have a better diversity of tests than we were getting with travis at the time. They're primarily for testing the current master + PRs against a range of distro supplied versions of our dependencies, as well as some 'alternate' features that we're not likely to get natively (i.e. arch and valgrind). The original bit of testing against Pillow was for ensuring that we're not going to break the build by throwing in docker images that weren't tested. 

So, given the current state of this repo, and the PRs against it, I think that:

1) It doesn't really make sense to test against stable
2) We should have the 'master' branch be the one that determines which images can be pushed to dockerhub. 

## Why not stable?

Well, frankly, we basically never test _anything_ against stable in the base repo. It's always master or master+ PR.  The only time we ever test against something derived from stable is on point releases, and then I'd argue that we should generally be passing whatever docker changes are in place. So why test them? They don't tell us anything useful, and they're slow. 

## Why master?

The point of the latest PRs is to improve coverage of tests, either by expanding the diversity of architectures or the diversity of what we're testing for. Since the point here is that there were errors on stable that are now ignored/fixed in master, having the success of the PR gated on passing stable is pretty much irrelevant. 

This has held up both the alternate arch PR and the valgrind PR, and I don't see that the extra effort or burned electrons is gaining us anything.

**Comment by hugovk** [comment]
Yep, makes sense. 

iirc we started with `stable` (easiest), then added `latest`. And like you say, we usually only care about `latest` (i.e. is what we have potentially releasable now?).

**Comment by radarhere** [comment]
Is this resolved now, given the merge of #109?

**Comment by wiredfool** [comment]
Yes, that's done now.
