### ISSUE TITLE
Docker removing Open Source projects

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/docker-images#171]
https://blog.alexellis.io/docker-is-deleting-open-source-images/

I don't think we're directly affected by this, because IIRC the pillow docker account is setup as a personal account, but we may have to think about rehosting onto github. 

More context: 

https://github.com/docker/hub-feedback/issues/2314

**Comment by hugovk** [comment]
https://hub.docker.com/u/pythonpillow says "Community User", unlike others such as https://hub.docker.com/u/trion that say "Community Organization", so hopefully we'll be fine.

**Comment by hugovk** [comment]
More info:

https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/

**Comment by hugovk** [comment]
We're fine for the time being, let's reopen if things change.
