### ISSUE TITLE
If I want to use this kind of transform color with option ImageCms.INTENT_ABSOLUTE_COLORIMETRIC, how to code it ?

### ISSUE THREAD

**Issue by creno0330** [python-pillow/docker-images#198]
if i want to use this kind of transform color with option  ImageCms.INTENT_ABSOLUTE_COLORIMETRIC,how to code it ?

_Originally posted by @digital-prepress in https://github.com/python-pillow/Pillow/discussions/6161#discussioncomment-2461007_

**Comment by radarhere** [comment]
Hi. I previously left a response to that comment at https://github.com/python-pillow/Pillow/discussions/6161#discussioncomment-2465138

If you would like a different answer, please provide more detail in your question.
