### ISSUE TITLE
Docker Hub hacked

### ISSUE THREAD

**Issue by hugovk** [python-pillow/docker-images#61]
https://news.ycombinator.com/item?id=19763413

@wiredfool Do we need to reset the password and update this?

https://github.com/python-pillow/docker-images/blob/0a0108595c9f5eaeae4b23e73a92e33ab0cc902e/.travis.yml#L31-L34

**Comment by wiredfool** [comment]
I haven't been notified, so I'm guessing no. Are we having trouble pushing?

**Comment by hugovk** [comment]
No, everything's working smoothly, just wanted to check.

**Comment by wiredfool** [comment]
We're not using autobuild on the docker side, we're doing this on travis. So there are no GH credentials on the account for them to remove.
